### ISSUE TITLE
SH2:EE Frequent White Flashing

### ISSUE THREAD

**Issue by LordFarfignewton** [elishacloud/Silent-Hill-2-Enhancements#509]
Hi there! Running into an issue where the game will inexplicably flash white randomly and constantly. Restarting doesn't fix the issue, and to make matters worse, it seems to cause the flashing to continue in other programs after the game is closed. This also does NOT happen to the whole screen after the game is closed; it becomes app-specific (so, for example, afterwards, when I was taking a peek at the.ini, Notepad became flashing as well. It's whatever app is in the foreground). Updating drivers also didn't fix this. While getting footage it seemed this may be happening after using the inventory menu but it also happens on startup sometimes so I'm not sure.

This happened very sparingly on my first playthrough of EE back in February, but it is MUCH worse now. The video file is too big, so I'll attack an unlisted video here. Flashing doesn't start until a ways in but I figured I should leave it uncut for you guys.

[d3d8.log](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/8537026/d3d8.log)
https://youtu.be/KwhO9K9E8g0

EDIT: New link, should work now

**Comment by LordFarfignewton** [comment]
Video upload seems to be stuck at 95%, if it doesn't figure itself out in a little bit I'll try reuploading

**Comment by Polymega** [comment]
Sorry you're having issues. If you restart your PC and _never_ launch the game, do you still experience white flashes? Does this only happen upon launching the game?

If you open the d3d8.ini file and set `d3d8to9 = 0` does this fix the problem? The fact that this keeps happening to other programs outside of Silent Hill 2 seems very odd to me.

@elishacloud he has the following errors in his log:
```
8988 22:37:01.927 Hook::HotPatch Error: 'CreateProcessA' is not patch aware at addr=76983AB0
8988 22:37:01.927 Bytes in memory are: \xCC\xCC\xCC\xCC\xCC\xE9\xD5\xC7\xED\xFF\x5D\xFF
8988 22:37:01.927 Hook::HotPatch Error: 'CreateProcessW' is not patch aware at addr=769688E0
8988 22:37:01.927 Bytes in memory are: \xCC\xCC\xCC\xCC\xCC\xE9\x65\x79\xEF\xFF\x5D\xFF
```

**Comment by LordFarfignewton** [comment]
> 

Yes, this only starts happening after booting up the game. Turning off DirectX8 to 9 did not fix it, and yeah this past time, it started flashing immediately without me checking my inventory. I'm not sure what the fix elisha referenced is or how I would use it, but if a newer build might do something with this that'd be sweet. I don't know the exact build I'm using but I got this set up in like January this year. Thanks for your helps you guys :)

**Comment by elishacloud** [comment]
Below is the latest build.  This should fix the errors you are see in the log file.

New build:  [d3d8.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/8546290/d3d8.zip)

**Comment by LordFarfignewton** [comment]
[d3d8.log](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/8546364/d3d8.log)

Thank you, but it appears that the issue still persists. Once again it was happening before I opened the inventory but the inventory seemed to make it worse (but this may be my imagination). I'm going to fiddle with the .ini and report back (i'll try the directx idea again and also dissabling UX).

**Comment by LordFarfignewton** [comment]
[d3d8.log](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/8546376/d3d8.log)

FIXED! I don't know why, but it seems windowed mode was causing the flashing. As far as I can tell without sitting down for a full play session, turning it off of windowed to borderless or fullscreen fixed the issue. Still seemed to be fixed after turning directx8-9 back on as well. I will be playing a lot more tomorrow if you want to keep this open until I can see if after an hour or two this holds true, but right now that seems to be it. Thanks for your help! :)

**Comment by elishacloud** [comment]
> I don't know why, but it seems windowed mode was causing the flashing.

Glad you figured it out.  It seems like you have something running on your computer that is causing the flashing.

**Comment by elishacloud** [comment]
@LordFarfignewton, would you be willing to test an update for me?

For this new build please test both `ScreenMode = 1` and `ScreenMode = 2`.  I would like to see if either of these screen modes work now.

Also, please attach your log file for `ScreenMode = 1` so I can see some of the items in it.

Here is the new testing build:  [d3d8.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/8953251/d3d8.zip)

**Comment by LordFarfignewton** [comment]
> @LordFarfignewton, would you be willing to test an update for me?
> 
> For this new build please test both `ScreenMode = 1` and `ScreenMode = 2`. I would like to see if either of these screen modes work now.
> 
> Also, please attach your log file for `ScreenMode = 1` so I can see some of the items in it.
> 
> Here is the new testing build: [d3d8.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/8953251/d3d8.zip)

I'd be happy to! Went and downloaded it, and I should have time to give it all a go tonight. Will report back!

**Comment by elishacloud** [comment]
@LordFarfignewton, thanks for being willing to test.  Could you test with this new update instead?  Please test all three screen modes.

Here is the new testing build: [d3d8.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/8970401/d3d8.zip)

**Comment by LordFarfignewton** [comment]
Alright, after having some time to test it seems that the behaviour of all 3 modes was the same. Windowed and Borderless Windowed, as well as Windowed at a smaller resolution with border, had the flicker, and Fullscreen was pretty much perfect. Here's the log of course.

[d3d8.log](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/8972930/d3d8.log)

**Comment by LordFarfignewton** [comment]
Went through and it was much the same. You may very well be right that this is something on my end, but it ONLY happens with SH2EE so I'm not sure what in tarnation.
[d3d8.log](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/8986055/d3d8.log)

**Comment by elishacloud** [comment]
The white flashes should be fixed with the latest update:  [d3d8.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/9005597/d3d8.zip)

**Comment by LordFarfignewton** [comment]
Alright, so the white flashes are definitely gone now, however now on screen modes 1 and 2 I was getting a _black_ flash instead. Still, this is muuuuch much better and easier to ignore, even if it's still as frequent, as it isn't blinding like the white flash lol. As per usual fullscreen didn't have any problems.
[d3d8.log](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/9007659/d3d8.log)

**Comment by LordFarfignewton** [comment]
YES both look perfect! That did it! Thanks for figuring that one out :) And congrats on the launch of the installer in a few days! I've tried to get many people to try this version and the process was a bit daunting for infrequent modders, so now they will have no excuse. Peace!
[d3d8.log](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/9016924/d3d8.log)

**Comment by elishacloud** [comment]
Thanks @LordFarfignewton.  Closing out this issue as fixed with the latest release.

**Comment by vampirecoffee** [comment]
FYI - I was having a similar issue with the latest release. In my case, it happens only in fullscreen mode, whether FrontBufferControl is set to 0 (the default) or 2.

Weirdly, when I try recording the behavior with OBS, OBS either records a black screen the whole time (if I'm using Monitor Capture) or it doesn't see any flashing at all (if I use Game Capture). I had to use my cell phone to take this video: https://vampirecoffee.net/mod_debugging/sh2ee/FLASHING.mov 

edit to attach d3d8.log 

[d3d8.log](https://github.com/user-attachments/files/30255252/d3d8.log)
