### ISSUE TITLE
SH2EEsetup not able to run. 

### ISSUE THREAD

**Issue by Ainz59** [elishacloud/Silent-Hill-2-Enhancements#588]
Hi, 

I'm having issues with my installer. I've gone through the troubleshooting forum and I saw someone else with a similar issue as mine and I saw that they were able to get the individual files(however I did try using their links and it doesn't work for me) for the Enhanced edition itself. I don't understand why my Installer won't run even when I give it admin perms and it's excluded from my anti-virus. It just gives me the "Files unavailable" error as you can see: 
![Silent](https://user-images.githubusercontent.com/112423313/187269734-8f304815-ef27-4c95-bab1-51a4f9716f5a.png)

**Comment by Polymega** [comment]
This should be resolved now. Please re-downloaded the Setup Tool from the project site: 
https://enhanced.townofsilenthill.com/SH2/install.htm#usingEE

See these tickets:
- https://github.com/elishacloud/Silent-Hill-2-Enhancements/issues/587
- https://github.com/elishacloud/Silent-Hill-2-Enhancements/issues/586

**Comment by Ainz59** [comment]
Still having the same error, I deleted the other one and re-downloaded via the link you sent just there: 
![image](https://user-images.githubusercontent.com/112423313/187274055-502310b8-46d9-4537-aec2-29abedf36e54.png) 

![image](https://user-images.githubusercontent.com/112423313/187274118-8c4cdd38-47d0-41f3-a6e1-10fdfbc28cf8.png)

**Comment by Polymega** [comment]
Just in case there's some sort of cache issue going on with your web browser, can you download it from here and try?
[SH2EEsetup.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/9447104/SH2EEsetup.zip)

If that doesn't work then, as silly as this might sound, maybe try restarting your PC. I've received reports here and on Twitter that the new update to the tool has fixed this issue, so I want to be sure.

**Comment by Ainz59** [comment]
That file you sent worked for me, but I'll clear the cache on my browser and let you know how that pans out and the classic turn it off and on: 
![5d5428de7b67de57d4ba471234852cf5](https://user-images.githubusercontent.com/112423313/187275123-923ee869-1e1d-433c-bcad-94fffe8d280c.png)

**Comment by Polymega** [comment]
Okay, phew, glad to know it's working for you now. I just grabbed the updated tool from the site and put it in a ZIP. It might be an odd cache issue or a simple mistake of saving the updated tool somewhere else and running the older tool.

**Comment by Ainz59** [comment]
I cleared the cache on my browser, mostly the image one because I clear the cookie cache every now and then and it's a pain to run through the "Decline" cookies all over again: 
![image](https://user-images.githubusercontent.com/112423313/187276037-733554dc-7e53-47ea-ae2e-9e49d27628c1.png)

I did try running the set-up tool from the site and it does work for me:  
![image](https://user-images.githubusercontent.com/112423313/187276337-14046fed-078a-4686-a686-188d1ec92073.png)

so I guess the fix is to have people clear the "cached images and files": 
![image](https://user-images.githubusercontent.com/112423313/187276499-494b0fd5-28c3-4612-8a00-f38f33c4a45c.png)

**Comment by Ainz59** [comment]
So yay. Also thanks for the amazing work you've done on the enhanced edition, I replay the game once a year. I can't recommend this game highly enough to people. Hopefully I won't have other problems from here on out.

**Comment by Polymega** [comment]
Glad it all worked out. The main reason this issue happened is on my end with backend web work. Things like site certificates, CDNs, and redirects all need to work _just right_ with each other and, if something is off, it can break things... and things were temporarily broken.

**Comment by Ainz59** [comment]
Listen, you're doing great work. It's just subtle things people don't think about such as clearing cache. I knew it was some sort of error between the setup and browser and I stressing because the website itself isn't down and I can download the set-up tool a dozen times. Thanks for the rapid response to my query.
