### ISSUE TITLE
Game closes after final boss 

### ISSUE THREAD

**Issue by Pieisnolie** [elishacloud/Silent-Hill-2-Enhancements#644]
Hello, the game closes after the final boss, when she falls to the ground and calls out your name and you shoot her the last time, the game will fade to black and close with no error message or sound everytime.

Whats different about my game: 
I used the build available here: https://github.com/elishacloud/Silent-Hill-2-Enhancements/issues/621
When I first started playing the game it would always make a loud beeping and crash after a few minutes, I looked around and tried this and it worked , 0 crashes, freezes and other issues for the rest of the game, until now. I imagine if i reverted to the original build it would go back to crashing ( Im only guessing ) 

I tried changing resolution ( fullscreen to windowed ) and restarting my PC, neither worked.
Also tried looking for open/closed issues about it and didn't find anything.

here's the log:
[d3d8.log](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/9885397/d3d8.log)

Video: https://streamable.com/4c874d

**Comment by Polymega** [comment]
I know you mentioned you tried that test build you linked, but can you try one more time with a new release we just pushed out?

You can grab this update to the SH2 Enhancements Module by either running the Setup Tool in Maintenance Mode and checking for updates:

![image](https://user-images.githubusercontent.com/27395260/198746434-162feecb-9967-44c7-b0f4-8093408054e5.png)

[Or by manually downloading here.](https://github.com/elishacloud/Silent-Hill-2-Enhancements/releases/latest) (We recommend updating through the Setup Tool if you installed the project using this tool, otherwise the tool will not know you have updated this package.)

-----------

If you don't mind, please let us know if you still experience this issue upon updating. We'll close the ticket after a little while if we don't hear back. Thanks

**Comment by Pieisnolie** [comment]
Thank you for the quick response :) , unfortunately after updating with the setup tool, it did not fix the issue, I tried twice to be sure 

here is the log if you need it: 
[d3d8.log](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/9892455/d3d8.log)

**Comment by Polymega** [comment]
I'm truly befuddled by this one. I'm just going to throw any idea I can think to try:

- Try moving the entire game folder to a new folder that doesn't have apostrophes in it.
- If you only ever played the game with a controller, try booting up the game with the controller disconnected.
- Temporarily disable "Run the game in DirectX 9" found on the first page of the `SH2EEconfig.exe` tool.
- Temporarily rename the `sh2e` folder to something else.
- Temporarily remove the `dsound.dll` and `dsoal-aldrv.dll` files from the game folder.
- Make a backup of your `\data\save\Folder 01\` folder. These are your save files.
   - [Redownload the "fully extracted version" of the base/vanilla game.](https://www.myabandonware.com/game/silent-hill-2-restless-dreams-bgd#download) Delete your `data` folder found in the game's main folder and place the `data` folder from the redownloaded game back in here. Then, place your backup save files back in `\data\save\Folder 01\`.

**Comment by Pieisnolie** [comment]
Hello! Success! I have tested out your suggestions and it went like this:
Moving game to new folder: Failure
No Controller: Failure
Disable "Run the game in DirectX 9": Failure
rename sh2e folder: Success! although I don't know if that was the solution, because when i renamed the folder and launched the game, it asked to update the Setup tool, so it mightve just been an update you guys put out :D 

And It does work with DirectX 9 Enabled, I tried a second time after renaming the file.

Thank you for the help! I think this means I can close the issue now?

**Comment by Polymega** [comment]
> rename sh2e folder: Success! although I don't know if that was the solution, because when i renamed the folder and launched the game, it asked to update the Setup tool, so it mightve just been an update you guys put out :D

I was afraid it'd be this. I don't understand what's happened/changed, but there are reports of people having issues with the game when this folder is in use. The `sh2e` folder houses **all** of our collateral project files. Improved audio, FMVs, upscaled images, HD font, etc. [More info on that can be read here.](https://enhanced.townofsilenthill.com/SH2/troubleshoot.htm#what-is-the-purpose-of-the-sh2e-folder)

Can you do me a favor? Rename the `sh2e` folder back to "sh2e" and, within this folder, _temporarily_ rename the `bg` folder and `pic` folder to something else. Then, see if the game still freezes at the end. 

If it doesn't, set the `bg` folder name back to its original name. Does it freeze? If not, set the 'pic' folder name back. Does it freeze? This could help us hone in on if it's a particular project package causing the issue.

**Comment by Pieisnolie** [comment]
sh2e folder > Renamed "pic" and "bg" : Game DOES NOT crash 
sh2e folder > Renamed "pic" ; "bg" changed back to original name : Game DOES crash
sh2e folder > Renamed "bg" ;  "pic" changed back to its original name: Game DOES NOT crash

Just to be clear, this means as far as i can tell the game only crashes at the end when the "bg" folder is being used. And it does not crash if the bg folder is renamed to something else

**Comment by Pieisnolie** [comment]
Yes that appears to have worked! The game does not crash at the end

**Comment by Polymega** [comment]
![ImprobableFarflungHapuka-max-1mb](https://user-images.githubusercontent.com/27395260/198895746-48c9b869-82de-4d01-9d36-e65e7f1c07f2.gif)

Phew... Okay I think we're good to close this out for real now. :)
