### ISSUE TITLE
Adding our own sounds on top of the game

### ISSUE THREAD

**Issue by Polymega** [elishacloud/Silent-Hill-2-Enhancements#834]
Hi Elisha,

For when the time comes, @mercury501 and I have done preliminary research, game-engine side, for this feature. This feature would be a two-part affair:

## 1. Replace the game's audio of "game start" and "save game" with our own.
If you remember, for the longest time we tried to preserve the "game start" sound when loading a save file while in-game. The issue being, upon loading a save file, this sound gets cut off with the rest of the sounds after the new save is loaded in.

The ask here is to monitor whenever the instruction is called to play this sound, intercept it, and have our project play the sound instead. Thus, it isn't impeded by any rules set by the game engine. I won't get into the boring details of why, but if we're going to do this it might be best to have our project intercept and play all instances of the "game start" and "save game" sounds then. I asked Mercury to help find these instructions and here's what we've came up with:

| Description | 1.0 | 1.1 | DC |
| -- | -- | -- | -- |
| "Start game" sound when starting a "NEW GAME" from the main menu | 0049870C | | |
| "Start game" sound when selecting "CONTINUE" from the main menu | 00497F84 | | |
| "Start game" sound when loading an existing save file | 00454A64 | | |
| "Save game" sound when saving via the red square save points | 0048C301 | | |
| "Save game" sound when saving via _Pause > Save Game_* | [See here](https://github.com/elishacloud/Silent-Hill-2-Enhancements/blob/master/Patches/SaveGameSound.cpp) | [See here](https://github.com/elishacloud/Silent-Hill-2-Enhancements/blob/master/Patches/SaveGameSound.cpp) | [See here](https://github.com/elishacloud/Silent-Hill-2-Enhancements/blob/master/Patches/SaveGameSound.cpp) |

*This never existed in vanilla SH2 PC and was added in by us as a feature. Perhaps this feature should be "absorbed/merged" into the audio handling feature being discussed here?

## 2. Adding flashlight toggle SFX
This was requested by a fan [in this ticket](https://github.com/elishacloud/Silent-Hill-2-Enhancements/issues/804) and, if we have the capability to add our own sounds for the request above, we should be able to accommodate this request as well. (Plus, it's a neat, novel effect.) The SFX for this was taken from SH3, where toggling the flashlight in that game does make a sound.

Here is the pseudo code for such a feature:

### Variables:
`FlashlightSwitch` = https://github.com/elishacloud/Silent-Hill-2-Enhancements/blob/master/Patches/Common.cpp#L31

`EventIndex` = https://github.com/elishacloud/Silent-Hill-2-Enhancements/blob/master/Patches/Common.cpp#L35

`CanUseFlashlight`
1.0: 01F7DC2C byte
1.1: 01F8182C byte
DC:  01F8082C byte

`WorldColorR`
1.0: 00942C50 byte
1.1: 00946850 byte
DC:  00945850 byte

`WorldColorG`
1.0: 00942C51 byte
1.1: 00946851 byte
DC:  00945851 byte

`WorldColorB`
1.0: 00942C52 byte
1.1: 00946852 byte
DC:  00945852 byte

_(`WorldColorR/G/B` variables could be useful for other applications; I'd recommend storing these in common.cpp)_

### Precursor:
Whenever `CanUseFlashlight` changes to `1`, take note of the value `FlashlightSwitch` is currently at and do not play any sound

### Pseudo code:
```c++
if /*[CHECK 1]*/ (FlashlightSwitch == changes its value while CanUseFlashlight == 1 && (RoomID != 0x24 /*Angela apt room*/ || 0x89 /*Maria in prison*/ ||  0x8F /*Eddie boss room 1*/ ||  0x90 /*Eddie boss room 2*/ ||  0xA2  /*Hotel room 312*/))  || /*[CHECK 2]*/ (FlashlightSwitch changes its value && (RoomID == 0X04 /*Town East*/ || 0X08 /*Town West*/) && (WorldColorR == 0 && WorldColorG == 0 && WorldColorB == 0)) {
	if FlashlightSwitch == 0 {
		play flashlight_off.wav
	}
	else if FlashLightSwitch == 1
		play flashlight_on.wav
	}
}
```

_(For [CHECK 2] , we don't monitor `CanUseFlashlight`; we just see if `FlashlightSwitch` changes value while in any of those RoomIDs while `WorldColorR/G/B` is 0)_

Special consideration that I don't know how to properly include as part of the pseudo code above:

```c++
if FlashlightSwitch changes its value && RoomID == 0xBB /*Final boss room */ && ANY CutsceneID has been triggered {
do NOT play any flashlight sounds from that point onwards while in this room
}
/* (reset this check whenever RoomID 0xBB goes away and comes back) */
```

------------------------

**Audio files for use:** 
[sounds.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/12448700/sounds.zip)

I'd recommend making this two separate features. Part 1 could be considered an **Audio Fix** and placed under _Audio > Audio Fixes_ within the Configuration Tool. Part 2 could be considered **Bonus Audio** and placed under an all new _Audio > Bonus Audio_ category within the Configuration Tool.

**Comment by matheusvb3** [comment]
Polymega, if I could make a suggestion, in the PS2 version when you switch between memory card folders in the save screen it makes a sound that goes unused in the PC version, would it be possible to add it for when you delete a saved file? It would fit perfectly, much more so than the generic "prompt confirmed" sound that gets used so often. I'm not if SH3 uses this sound either since you can't switch the memory card you'll use in that game's save screen, from what I remember.

**Comment by Happyfaceman91** [comment]
If that proves possible, do you think it would be possible to intercept the footsteps and replace them with random ones that have more variations than just one? Asking because I have the original sound sources that Akira used for most of the player footstep sounds (and in even higher quality than the ps2 versions, contrary to what a lot of people seem to think Akira didn’t record any of them himself) but I don’t know the feasibility of making an asi or something that replaces them with more variations. I want to make a mod that does that but I’m a sound designer, don’t know too much about code so I thought I’d ask here.

**Comment by elishacloud** [comment]
I added some basic code to play a wav file file when the flashlight turns on or off.  Much of it is hard coded for now and I did not implement the final boss room exclusions.

You can check it out [here](https://github.com/elishacloud/Silent-Hill-2-Enhancements/actions/runs/6912687616).

Note: it is looking for the wav files under: `sh2e\sound\extra\`

**Comment by Polymega** [comment]
Thanks, Elisha! I haven't done a full playthrough test with it yet, but I tested quite a few key areas in 1.0 relating to the pseudo code I sent. And I'm tickled pink to say that the pseudo code and, subsequently, your actual code for the flashlight noise so far is super solid!

There's just one part that I missed in the psuedo code I sent you and I'll probably need @AeroWidescreen's help with this:

For `[CHECK 1]`, we need to **remove** Hotel Room 312 from it and turn this room into its own `[CHECK 3]`. So something like:

```c++
(other checks before this) ||  /*[CHECK 3]*/ (FlashlightSwitch == changes its value && (RoomID == 0xA2  /*Hotel room 302*/) && VHSTape is NOT in player's inventory)
```

@AeroWidescreen I need your help for the "VHSTape is NOT in player's inventory" part. Can you assist Elisha in the code to determine this? After you view the video tape, you are then able to toggle your flashlight again while in this room. I didn't catch this in my original pseudo code for this.

**Comment by Polymega** [comment]
Er, I forgot to test the outdoor areas at night. This part of the code isn't working:

```c++
/*[CHECK 2]*/ (FlashlightSwitch changes its value && (RoomID == 0X04 /*Town East*/ || 0X08 /*Town West*/) && (WorldColorR == 0 && WorldColorG == 0 && WorldColorB == 0))
```

Perhaps this is happening because `[CHECK 1]` needs Room 0x04 and 0x08 added to its `RoomID =!` check?

**Comment by AeroWidescreen** [comment]
@elishacloud 
If the byte at `01F7A7E2` is greater than **0x7F** then the Videotape will always be in the player's inventory. Any value less than **0x80** means the Videotape is not present.

1.0: 01F7A7E2
1.1: 01F7E3E2
DC: 01F7D3E2

You can find more information about this memory address here:

https://github.com/Polymega/SilentHillDatabase/blob/2e2b38c79308a82f42df7ff68124a1531eb7f69b/SH2/SH2%20PC%20memory%20addresses#L216

**Comment by elishacloud** [comment]
The latest check-in should finish the criteria for the flashlight.

> For `[CHECK 1]`, we need to **remove** Hotel Room 312 from it and turn this room into its own `[CHECK 3]`.

Done.

> This part of the code isn't working:
> Perhaps this is happening because `[CHECK 1]` needs Room 0x04 and 0x08 added to its `RoomID =!` check?

I fixed this. If your previous pseudo code was good it should work now.

There are still a few caveats:

* This setting is still hard coded on.
* The volume is still hard coded to max, does not honor the sliders yet.
* No code added yet for the game start/continue or game save.

**Comment by Polymega** [comment]
> For [CHECK 1], we need to remove Hotel Room 312 from it and turn this room into its own [CHECK 3].

This one isn't working correctly. Using Aero_'s notes above, the pseudo code should be something like: 

```c++
(FlashlightSwitch == changes its value && RoomID == 0xA2 /*Hotel room 312*/ && 01F7A7E2 < 0x80 /* VHS tape is not in player's inventory */)
```

-------------------

> Special consideration that I don't know how to properly include as part of the pseudo code above:

```c++
if FlashlightSwitch changes its value && RoomID == 0xBB /*Final boss room */ && ANY CutsceneID has been triggered {
do NOT play any flashlight sounds from that point onwards while in this room
}
/* (reset this check whenever RoomID 0xBB goes away and comes back) */
```

This one also isn't working. The flashlight continues to make a clicking noise after a cutscene initiates while in this room.

------------------

> The volume is still hard coded to max, does not honor the sliders yet.

No problem. I did notice that it already honors the Master Volume slider. It would just need to also honor the SFX slider as well (as the flashlight sounds should be classified as a SFX). On that note: When the time comes, the game start/game load sounds should probably also be classified as SFX.

**Comment by elishacloud** [comment]
> This one isn't working correctly. Using Aero_'s notes above, the pseudo code should be something like:

This one should be fixed now.  I had a mistake here.

> This one also isn't working. The flashlight continues to make a clicking noise after a cutscene initiates while in this room.

Fixed.  I had an issue here too.

**Comment by elishacloud** [comment]
Ok, I had one more issue.  Try this one instead:  https://github.com/elishacloud/Silent-Hill-2-Enhancements/actions/runs/6923918214

**Comment by Polymega** [comment]
> Ok, I had one more issue. Try this one instead: https://github.com/elishacloud/Silent-Hill-2-Enhancements/actions/runs/6923918214

Thanks! There's still some issues with both:

> This one isn't working correctly. Using Aero_'s notes above, the pseudo code should be something like:

Unfortunately this one isn't working at all. You can provoke the flashlight noise a t all times while in Room 0xA2, whereas we only want to provoke it once the VHS tape is no longer in the player's posession while in the room.

> This one also isn't working. The flashlight continues to make a clicking noise [in the final boss room] after a cutscene initiates while in this room.

This has been fixed while in the room, but a 'bug' presents itself now where, whenever you leave the room (such as the game proceeding to the ending cutscene that's in a different room, or loading another save file while in this room, etc) the code will play the flashlight toggle noise once upon such a change happening. In short: The flashlight toggle noise looks to happen after Room 0xBB unloads.

**Comment by elishacloud** [comment]
Ok, one more time.

> You can provoke the flashlight noise a t all times while in Room 0xA2, whereas we only want to provoke it once the VHS tape is no longer in the player's posession while in the room.

This was caused by:

> For `[CHECK 1]`, we need to **remove** Hotel Room 312 from it and turn this room into its own `[CHECK 3]`.

I added Hotel Room 312 back into `[CHECK 1]`.  This should solve this issue.

> In short: The flashlight toggle noise looks to happen after Room 0xBB unloads.

It seems like the game is toggling the flashlight usage for the user when switching rooms.  I made it so that the game ignores the change that happens _immediately_ after exiting the boss room.  Hopefully this fixes it.

_You can test it [here](https://github.com/elishacloud/Silent-Hill-2-Enhancements/actions/runs/6924285273)._

**Comment by Polymega** [comment]
Unfortunately it's a no-go for Hotel Room 312. The flashlight toggle noise is still happening at all times while in this room.

Also, the toggle noise now no longer happens, in the general sense. It'll still play in Hotel Room 312, for example, but not while playing the game in general. 

> It seems like the game is toggling the flashlight usage for the user when switching rooms. I made it so that the game ignores the change that happens immediately after exiting the boss room. Hopefully this fixes it.

I was unable to test this due to the aforementioned issue right above.

**Comment by elishacloud** [comment]
Oops.  It was supposed to be not-equals, I put it as equals.  Try it again [here](https://github.com/elishacloud/Silent-Hill-2-Enhancements/actions/runs/6924377839).

**Comment by Polymega** [comment]
Quick tests and everything looks to check out! I'll do a proper playtest in the near future for this. Great work and thank you!

**Comment by Polymega** [comment]
@elishacloud 
I found an outlier case with the flashlight noise. To fix this:

`CanUseFlashlight2`
1.0: 01FB7F0D byte
1.1: 
DC: 

--------------

The change would be:

### Precursor:
Whenever `CanUseFlashlight` changes to `1`, take note of the value `FlashlightSwitch` is currently at and do not play any sound

```c++
/*[CHECK 1]*/ (FlashlightSwitch == changes its value while CanUseFlashlight == 1 && (RoomID != 0x24 /*Angela apt room*/ || 0x89 /*Maria in prison*/ ||  etc etc etc))
```

-----------------

It'd be changed to something like:

### Precursor:
Whenever `CanUseFlashlight` & `CanUseFlashlight2` changes to `1`, take note of the value `FlashlightSwitch` is currently at and do not play any sound

```c++
/*[CHECK 1]*/ (FlashlightSwitch == changes its value while (CanUseFlashlight == 1 && CanUseFlashlight2 == 1) && (RoomID != 0x24 /*Angela apt room*/ || 0x89 /*Maria in prison*/ ||  etc etc etc))
```

^ The change above is from `CanUseFlashlight == 1` to `(CanUseFlashlight == 1 && CanUseFlashlight2 == 1)`.

**Comment by elishacloud** [comment]
I made the change, but it does not seem to work.

**Comment by Polymega** [comment]
> Edit: Maybe it would help if you told me what the outlier case is?

Sure. In some scenarios, when you enter a new room an in-game cutscene immediately plays. For some of these cutscenes, they require James' flashlight to be on, so the game turns it on automatically on James' behalf. When this happens, you hear the toggle noise as the cutscene starts. By and large, this isn't _too_ big of a deal, except this scenario also happens during the final cutscene (where James reunites with his wife on her sick bed). We especially don't want this to happen there.

The problem is, the game changes the value of `FlashlightSwitch` after the RoomID change but _before_ any cutscene ID triggers, so we **can't** do a simple code of "if cutsceneID != 0x00 then don't play any flashlight sounds".

Hopefully that made sense. I'll be investigating this some more and will circle back with you.

**Comment by elishacloud** [comment]
What if we just ignore the change when the RoomID changes, like we do with the boss room?

I put a test fix in for this.  Let me know if this helps.

**Comment by Polymega** [comment]
> What if we just ignore the FlashlightSwitch when the RoomID changes, like we do with the boss room?
> I put a test fix in for this. Let me know if this helps.

Unfortunately, it doesn't work. This is because it happens in this type of sequence: RoomID change > `FlashlightSwitch` value is changed > Cutscene or FMV starts (if applicable). In other words, the `FlashlightSwitch` toggle doesn't happen on the same frame as the RoomID change. 

------------

[In regards to this build](https://github.com/elishacloud/Silent-Hill-2-Enhancements/actions/runs/6933761324), I should also mention: The `CanUseFlashlight2` I suggested actually fixes the issue mentioned above. However, it presents a new issue of, whenever you're in a room where the flashlight is dead (but you can still toggle it to try), it no longer plays the `flashlight_on.wav` file. This is because, whenever there is text on the screen, `CanUseFlashlight2` changes to `0`.

https://github.com/elishacloud/Silent-Hill-2-Enhancements/assets/27395260/bee72763-453e-46a6-bb00-100d8b6886f9

^ Because there's text that says, "I pressed the switch, but nothing happens" `CanUseFlashlight2` changes to `0` while the text is on-screen so `flashlight_on.wav` doesn't play.

I'm thinking maybe we add a new check that excludes rooms where the flashlight is dead inside of them.

**Comment by Polymega** [comment]
I didn't catch your edit. I'll test this build right now: https://github.com/elishacloud/Silent-Hill-2-Enhancements/actions/runs/6934423803

**Comment by Polymega** [comment]
Unfortunately [this build](https://github.com/elishacloud/Silent-Hill-2-Enhancements/actions/runs/6934423803) also doesn't fix it. May I ask you to share the code used for all the conditional checking for this here? It'd help me wrap my head around how I could submit a possible solution for this.

**Comment by elishacloud** [comment]
Here is the check's I am using so far:  https://github.com/elishacloud/Silent-Hill-2-Enhancements/blob/fdd2d8cfddd3d780c2ed157a6763bf58074a8453/Patches/PlayWavSound.cpp#L59-L74

**Comment by Polymega** [comment]
Thank you. Alrighty, here's my proposal to hopefully get everything done and squared away with this:

To start, revert the code back to [this build](https://github.com/elishacloud/Silent-Hill-2-Enhancements/actions/runs/6933761324) (that uses also uses `CanUseFlashlight2`).

I don't know how to write this as pseudo code for you, but essentially:

Revert the code back to using `CanUseFlashlight2` and **exclude** the rooms below from the `(CanUseFlashlight == 1 && CanUseFlashlight2 == 1)` part of the check:

```c++
0x06 /* Prison bug room */, 0xB5 /* Hotel Alternate 3F Hallway */, 0xB2 /* Hotel Alternate W 2F Hallway */, 0xB0 /* Hotel Alternate Reading Room */, 0xB1 /* Hotel Alternate 2F W Rooms Hallway */,  0xB4 /* Hotel Alternate 2F E Rooms Hallway */, 0xB3 /* Hotel Alternate E 2F Hallway */, 0xB8 /*Hotel Alternate Bar Entrance */, 0xB6 /*Hotel Alternate Bar */, 0xB7 /*Hotel Alternate Bar Kitchen */, 0xB9 /* Hotel Alternate 1F Employee Hallway */, 0xAA /* Hotel Alternate Angela Staircase */, 0xAB /* Hotel Alternate Employee Staircase */, 0xAE /* Hotel Alternate Burned Employee Area */, 0xAF /* Final Nine Save Squares */, 0xAC /* Final RPT Boss Fight Room */, 0xAD /*Hotel Alternate Back Hallway */, 0xBA /* Final Hallway Before End */, 0xBB /* Final Boss Room */
```

Not that I excluded `0xBB /* Final Boss Room */` in that list. This room has its own, special code to disable the noise after any cutscene ID has been triggered. For room `0xBB`, you probably want [to do something similar to the original proposal for the room](https://github.com/elishacloud/Silent-Hill-2-Enhancements/issues/834#issue-1868610116), which is to _only_ monitor `FlashlightSwitch` while in this room (and stopping noise after any cutscene ID has been triggered in here).

**Comment by Polymega** [comment]
I had a typo for the prison bug room. It should be `0x65` and not `0x06`

**Comment by elishacloud** [comment]
> Revert the code back to using `CanUseFlashlight2`

Ok, understood.

> **exclude** the rooms below from the `(CanUseFlashlight == 1 && CanUseFlashlight2 == 1)` part of the check

When you say exclude do you want me to add these rooms to the exclusion list?  Is it that you want some rooms to check only `CanUseFlashlight` and other rooms to check both `CanUseFlashlight` and `CanUseFlashlight2`?  If so can you give me a list of rooms to check both `CanUseFlashlight` and `CanUseFlashlight2`?

**Comment by Polymega** [comment]
> When you say exclude do you want me to add these rooms to the exclusion list?

Yes, please. So for those excluded rooms, they're just looking out for a change in `FlashlightSwitch`; they're not worried about `CanUseFlashlight` or `CanUseFlashlight2`.

> If so can you give me a list of rooms to check both CanUseFlashlight and CanUseFlashlight2?

This is what we want the default behavior to be. We then need to include a list of excluded rooms from this check. The excluded rooms include RoomIDs from [here](https://github.com/elishacloud/Silent-Hill-2-Enhancements/issues/834#issuecomment-1819660132) and [here](https://github.com/elishacloud/Silent-Hill-2-Enhancements/issues/834#issue-1868610116) (mentioned in `[CHECK 1]`).

Thanks!

**Comment by Polymega** [comment]
This might be a better breakdown of everything:

### Default behavior
**Unless a Room ID is specified:**
Monitor `CanUseFlashlight` and `CanUseFlashlight2`. If `FlashlightSwitch` changes values while both == 1, play SFX.

### Only monitor `FlashlightSwitch`
For these rooms, only monitor `FlashlightSwitch` for a value change. Don't monitor `CanUseFlashlight` or `CanUseFlashlight2` while in these rooms. If `FlashlightSwitch` changes value, play SFX:
```c++
0x65 /* Prison bug room */, 0xB5 /* Hotel Alternate 3F Hallway */, 0xB2 /* Hotel Alternate W 2F Hallway */, 0xB0 /* Hotel Alternate Reading Room */, 0xB1 /* Hotel Alternate 2F W Rooms Hallway */,  0xB4 /* Hotel Alternate 2F E Rooms Hallway */, 0xB3 /* Hotel Alternate E 2F Hallway */, 0xB8 /*Hotel Alternate Bar Entrance */, 0xB6 /*Hotel Alternate Bar */, 0xB7 /*Hotel Alternate Bar Kitchen */, 0xB9 /* Hotel Alternate 1F Employee Hallway */, 0xAA /* Hotel Alternate Angela Staircase */, 0xAB /* Hotel Alternate Employee Staircase */, 0xAE /* Hotel Alternate Burned Employee Area */, 0xAF /* Final Nine Save Squares */, 0xAC /* Final RPT Boss Fight Room */, 0xAD /*Hotel Alternate Back Hallway */, 0xBA /* Final Hallway Before End */, 0xBB /* Final Boss Room */
```

### Special consideration: Hotel Room 312
While in room `0xA2 /* Hotel Room 312*/, don't play SFX until the VHS tape is no longer in the player's inventory.

### Special consideration: Final boss room
While in room `0xBB /* Final boss room*/, once _any_ cutscene ID has been triggered, don't play SFX moving forward while in this room.

### Never play SFX in these rooms
No matter what, never play the flashlight SFX in these rooms:
```c++
RoomID != 0x24 /*Angela apt room*/ || 0x89 /*Maria in prison*/ ||  0x8F /*Eddie boss room 1*/ ||  0x90 /*Eddie boss room 2*/ ||  0xA2  /*Hotel room 312*/
```

**Comment by Polymega** [comment]
Had some typos in that post. Edited to fix them. Making a new post to make you aware in case you read it over email.

**Comment by elishacloud** [comment]
I am having trouble with this working.

> **Unless a Room ID is specified:**
> Monitor `CanUseFlashlight` and `CanUseFlashlight2`. If `FlashlightSwitch` changes values while both == 1, play SFX.

I am in room 0x15 and with this criteria when I turn off or on the flashlight I don't hear any sound.  Anytime I use `CanUseFlashlight2` the flashlight sound stops working.

**Comment by Polymega** [comment]
Your earlier build with `CanUseFlashlight2` works for me here. It sounds like you might not have the flashlight yet? Wood Side 2F Hallway (room 0x15) is the hallway right before you enter the room to acquire the flashlight.

To test, load _the second_ **Apartment SW Staircase** save (near the top of the save list), go up the flight of stairs, and back into that hallway to re-test.

**Comment by elishacloud** [comment]
> To test, load _the second_ **Apartment SW Staircase** save (near the top of the save list), go up the flight of stairs, and back into that hallway to re-test.

The flashlight sound is not working there either.  As long as I have the `CanUseFlashlight2` in there it does not work in that room either.

**Comment by Polymega** [comment]
Hmm... `CanUseFlashlight2` is `1` in these areas. To be sure:

`CanUseFlashlight2`
1.0: 01FB7F0D byte
1.1: 01FBBB0D byte
DC: 01FBAB0D byte

**Comment by elishacloud** [comment]
> Hmm... `CanUseFlashlight2` is `1` in these areas. To be sure:
> 
> `CanUseFlashlight2` 1.0: 01FB7F0D byte 1.1: 01FBBB0D byte DC: 01FBAB0D byte

Yes.  I also tried logging `CanUseFlashlight2` and it always equaled `0` when turning on or off the flashlight in the second Apartment SW Staircase save (as well as the Apartments 2F save).

**Comment by elishacloud** [comment]
BTW: here is the code in case you want to see it.  You can also download the build for this [here](https://github.com/elishacloud/Silent-Hill-2-Enhancements/actions/runs/6937089911).

https://github.com/elishacloud/Silent-Hill-2-Enhancements/blob/6bce1b99b8f75ef7a17784ca58e335623582c098/Patches/PlayWavSound.cpp#L26-L120

**Comment by Polymega** [comment]
So strange, as `CanUseFlashlight2` is working correctly and fine for me.

Thanks for this new test build. With the new test build, I found these problems:

-------------

I am able to toggle the flashlight SFX in rooms where it should never be toggleable. Looking at your code above, it's because the no-go rooms are categorized as part of `RoomRequiresNoChecking` whereas these rooms should probably be in its own category such as `RoomNeverPlaySFX` or something. 

[See this post](https://github.com/elishacloud/Silent-Hill-2-Enhancements/issues/834#issuecomment-1819931418), at the bottom, labeled "Never play SFX in these rooms" for the rooms in question.

----------------------

For Hotel Room 312, I can toggle the SFX at all times, whereas it should only happen after the video tape leaves the player's inventory.

**Comment by elishacloud** [comment]
> So strange, as `CanUseFlashlight2` is working correctly and fine for me.

It does not work for me.  Not sure what is different.  I am using binary v1.0.  I even tried loading several other saves and I am not getting any sound when I turn on or off the flashlight as long as `CanUseFlashlight2` is in the criteria.

> I am able to toggle the flashlight SFX in rooms where it should never be toggleable.

Should be fixes with the latest check-in.

> For Hotel Room 312, I can toggle the SFX at all times

Should be fixes with the latest check-in.

You can test it [here](https://github.com/elishacloud/Silent-Hill-2-Enhancements/actions/runs/6937729185).

**Comment by Polymega** [comment]
Thanks, Elisha. On my end, everything is fixed/adjusted/accounted for. Now, we just need to figure out the `CanUseFlashlight2` situation on your end...

**Comment by elishacloud** [comment]
I tried using the default settings in the Launcher, I tried with all three binary files (v1.0, v1.1, vDC), I tried multiple different saves.  As long as `CanUseFlashlight2` is in the criteria I am not getting any flashlight sounds.  If I remove `CanUseFlashlight2` then it works perfectly.

**Comment by Polymega** [comment]
@mercury501 figured out what's going on. If you set default movement speed to RUN then the value will be 1. If it's set to WALK or ANALOG/TOGGLE then it'll be 0.

I'll search for an alternative. Standby.

**Comment by Polymega** [comment]
@elishacloud 
May I ask you to send me a test build with `CanUseFlashlight2` changed to the following:

1.0: 01F7AE80
1.1: TBD
DC: TBD

_I'm not gonna bother finding the 1.1/DC addresses yet until I test 1.0_

Next we need to change it's conditional check. For this new `CanUseFlashlight2`, we want it to == 0. So it'd change from `CanUseFlashlight1 == 1 && CanUseFlashlight2 == 1` to `CanUseFlashlight1 == 1 && CanUseFlashlight2 == 0` .

Thanks

**Comment by elishacloud** [comment]
I created an update with the new addresses [here](https://github.com/elishacloud/Silent-Hill-2-Enhancements/actions/runs/6950763757).

**Comment by Polymega** [comment]
Thanks, Elisha. Everything looks to check out with this change. Can you do a few tests on your end to make sure you hear the noise now? If so, it should be good for committing. Here are all the addresses for this new `CanUseFlashlight2`:

1.0: 01F7AE80
1.1: 01F7EA80
DC: 01F7DA80

**Comment by elishacloud** [comment]
That works for me.  [This](https://github.com/elishacloud/Silent-Hill-2-Enhancements/actions/runs/6952205258) one should have everything working for the flashlight.

ToDo:
* Adjust the volume based on the in-game SFX volume
* Add sounds for start game and game save
* Add option to enable/disable these new sounds effects

**Comment by mercury501** [comment]
> That works for me. [This](https://github.com/elishacloud/Silent-Hill-2-Enhancements/actions/runs/6952205258) one should have everything working for the flashlight.
> 
> ToDo:
> 
>     * Adjust the volume based on the in-game SFX volume
> 
>     * Add sounds for start game and game save
> 
>     * Add option to enable/disable these new sounds effects

For the second point, I wrote [this](https://github.com/mercury501/Silent-Hill-2-Enhancements/commit/1ec05de9fcb82897a317166728afbc0a63a9526a) some time ago for the load and save sounds, check it out!

**Comment by elishacloud** [comment]
> For the second point, I wrote [this](https://github.com/mercury501/Silent-Hill-2-Enhancements/commit/1ec05de9fcb82897a317166728afbc0a63a9526a) some time ago for the load and save sounds, check it out!

Nice.  Thanks.

**Comment by elishacloud** [comment]
@mercury501, what does the `return 0x10;` do?

**Comment by mercury501** [comment]
@elishacloud my memory is a bit cloudy, but I think the "playsound" function returns 0x10 when it's successful, although it's return value doesn't seem to be used in the calls listed in my code

**Comment by elishacloud** [comment]
@mercury501, I noticed you had a "//TODO addresses" on the `LoadGameSoundPauseMenu` variable.  What was the ToDo for?  The current address you have here seems to work for me.

Here is a test build:  https://github.com/elishacloud/Silent-Hill-2-Enhancements/actions/runs/6962854871

**Comment by mercury501** [comment]
@elishacloud the TODO is for dialing in those addresses, they're only for 1.0

**Comment by Polymega** [comment]
> @mercury501, I noticed you had a "//TODO addresses" on the `LoadGameSoundPauseMenu` variable. What was the ToDo for? The current address you have here seems to work for me.
> 
> Here is a test build: https://github.com/elishacloud/Silent-Hill-2-Enhancements/actions/runs/6962854871

This is quite unreal... After so many discussions, theories, tests, and attempts at preserving these sounds, I thought this would never come to fruition. But silly me ever doubting the genius and ingenuity of our team. 😁 

Elisha and Mercury... you guys are the best! I'll get to testing this proper in the near future. 

@elishacloud down the line, [can this patch](https://github.com/elishacloud/Silent-Hill-2-Enhancements/blob/master/Patches/SaveGameSound.cpp) be "absorbed" into your work here, so that the "Save Game" sound the patch calls will instead be played through your audio handling solution, the same as the others?

**Comment by elishacloud** [comment]
> @elishacloud the TODO is for dialing in those addresses, they're only for 1.0

I see.  Ok, I will do that.

> @elishacloud down the line, [can this patch](https://github.com/elishacloud/Silent-Hill-2-Enhancements/blob/master/Patches/SaveGameSound.cpp) be "absorbed" into your work here, so that the "Save Game" sound the patch calls will instead be played through your audio handling solution, the same as the others?

Done.

**Comment by elishacloud** [comment]
Ok, I think it is ready to be tested, with this build [here](https://github.com/elishacloud/Silent-Hill-2-Enhancements/actions/runs/6963977613).

A few comments:
1. The feature is still hard coded 'on'.  I will need to make a configurable option for this later. 
2. I noticed that when exiting from the game it will play the save game sound.  Not sure if this is correct.
3. The start/save game sounds only work on binary v1.0.  I'll fix this later.
4. The volume is still hard coded to max.

Are all of these sounds supposed to be controlled by the SFX volume bar?  If anyone remembers how to determine what level the SFX volume bar is let me know.  I remember we looked this up before for another feature, but I forgot what it was.

**Comment by elishacloud** [comment]
> If anyone remembers how to determine what level the SFX volume bar is let me know. I remember we looked this up before for another feature, but I forgot what it was.

Ok, I found it [here](https://github.com/Polymega/SilentHillDatabase/blob/2e2b38c79308a82f42df7ff68124a1531eb7f69b/SH2/SH2%20PC%20memory%20addresses#L150C19-L150C27)

**Comment by Polymega** [comment]
> I noticed that when exiting from the game it will play the save game sound. Not sure if this is correct.

Yeah, that's not behaving correctly. It's also stopping any other sound your code was playing dead in its tracks. To test, click CONTINUE from the main menu or load a save file from LOAD GAME and then _quickly_ press Esc > Save Game. When you do this, the "Load Game" SFX will cut off prematurely and the "Save Game" SFX will take its place.

**Comment by elishacloud** [comment]
> Yeah, that's not behaving correctly.

That is caused by merging [this](https://github.com/elishacloud/Silent-Hill-2-Enhancements/blob/40b4b4b5cdb3ead8ee81bb2d7fef426a81b24666/Patches/SaveGameSound.cpp#L48) line of code in the SaveGameSound, when I replace that call with the new call to play the save sound.  Apparently, that line of code should be playing a different SFX.

> It's also stopping any other sound your code was playing dead in its tracks.

This is because I share the same buffer with the save and load sounds.  Only one can be played at a time.  I did not know that we needed to allow both the save and load sounds to be played at the same time.

Ok, I think both issues should be addressed now.  Also, I added code to set the correct volume level based on the SFX slider.

**Comment by elishacloud** [comment]
The [latest build](https://github.com/elishacloud/Silent-Hill-2-Enhancements/actions/runs/6973118131) should be complete here.

**Comment by Polymega** [comment]
Elisha, you nailed it!!! Tested on all binaries and things are working smoothly. Thank you a million times to both you and Mercury for this. <3

**Comment by Polymega** [comment]
1. Yes, they are.
2. Yep, that should be fine!
3. Sure thing.

Under ** Audio > Audio Fixes**:
```ini
PreserveSoundsOnLoad = 1
; Preserves the "game load" and "game save" sound effects when loading/saving while in-game. Otherwise, these sounds would be cut off prematurely under certain circumstances. Note: g_start.wav and save_sound.wav must be present in "sh2e\sound\extra\" for this feature to work.
```

Under **Audio > Bonus Audio**:

```ini
FlashlightToggleSFX = 1
; Enables a flashlight sound effect when turning the light on or off.  Note: flashlight_on.wav and flashlight_off.wav must be present in "sh2e\sound\extra\" for this feature to work.

**Comment by elishacloud** [comment]
@Polymega, Ok, I updated the names and descriptions.  One thing we did not discuss is if we wanted to use the sound effects from the `sddata.bin` rather than having them in the "sh2e\sound\extra\" folder.  I don't know if the flashlight sounds are there.  But I know that the save and start sounds are there.  Anyways, it is just a thought, if we want to keep things consistent.

**Comment by Polymega** [comment]
> One thing we did not discuss is if we wanted to use the sound effects from the sddata.bin rather than having them in the "sh2e\sound\extra" folder. I don't know if the flashlight sounds are there.

Oh! I didn't know you had the capability to do such a thing. The only possible caveat is that these sounds are located in voice.af. While they're in the "dialogue" file, they should be treated/considered as SFX, which is why we have them obeying the SFX slider.

- https://github.com/elishacloud/Silent-Hill-2-Enhancements/blob/master/AudioScripts/Dialog/Dialog-Map.csv#L42
- https://github.com/elishacloud/Silent-Hill-2-Enhancements/blob/master/AudioScripts/Dialog/Dialog-Map.csv#L132

The flashlight sounds _do not_ exist in sdatta.bin or elsewhere; this is something entirely new added by us.

Thanks!

**Comment by elishacloud** [comment]
> Oh! I didn't know you had the capability to do such a thing.

Yes, pulling a wav out of the `sddata.bin` file is pretty easy

> The only possible caveat is that these sounds are located in `voice.asf`.

Ok, that is possible, but not something I want to look into at this point.  Let's keep them in the "extra" folder for now.
